docs/granted/getting-started.mdx
docs/granted/security.md

Updated Granted version to v0.3.0

[New Release] Update versions (0.3.0)

---

docs/granted/getting-started.mdx
docs/granted/security.md

Updated Granted version to v0.3.1

[New Release] Update versions (0.3.1)

---

docs/granted/usage/console.md

Fix service map link to Granted CLI codebase

---

docs/approvals/deploying-granted/02-setup.mdx

Updated gdeploy version to v0.7.1

[New Release] Update gdeploy to (0.7.1)

---

docs/granted/configuration.md
docs/granted/usage/automatic-config-generation.md
docs/granted/usage/storing-iam-credentials-securely.md

Docs to go with https://github.com/common-fate/granted/pull/254

Granted credentials command

---

docs/granted/getting-started.mdx
docs/granted/security.md
docs/granted/usage/automatic-config-generation.md

Updated Granted version to v0.4.0

[New Release] Update versions (0.4.0)

---

docs/approvals/deploying-granted/02-setup.mdx

Updated gdeploy version to v0.8.0

[New Release] Update gdeploy to (0.8.0)

---

docs/approvals/sso/00-sso-setup.md
docs/approvals/sso/aws-sso.mdx
static/img/sso/aws-sso/add-application.png
static/img/sso/aws-sso/application-metadata.png
static/img/sso/aws-sso/assign-users.png
static/img/sso/aws-sso/attribute-mappings.png
static/img/sso/aws-sso/custom-application.png
static/img/sso/aws-sso/edit-attribute-mappings.png

Draft Docs with IAM role as cloudformation and json

AWS SSO identity provider

---

docs/approvals/deploying-granted/02-setup.mdx

Updated gdeploy version to v0.8.1

[New Release] Update gdeploy to (0.8.1)

---

docs/approvals/migration.md
src/css/custom.css
static/img/migration/no-accounts.png
static/img/migration/update-stack.png

Details the new IAM permissions required for Org Unit access rules and how to update the SSO Access Handler role.

Add migration guide for v0.9.0

---

docs/approvals/deploying-granted/02-setup.mdx

Updated gdeploy version to v0.9.1

[New Release] Update gdeploy to (0.9.1) [DOC-56]

---

docs/approvals/configuration/slack.md
static/img/approvals-getting-started/18-slacksetup.png
static/img/approvals-getting-started/19-slack-incoming-webhooks.png
static/img/approvals-getting-started/20-slack-channel-selection.png

Here is a preview of the slack webhook docs,
Things left to do: edit for writing style using copy guide,

initial docs for slack webhooks [DOC-57]

---

docs/approvals/deploying-granted/02-setup.mdx

Updated gdeploy version to v0.10.0

[New Release] Update gdeploy to (0.10.0)

---

docs/approvals/configuration/waf.md

Note known bad ACLs and browser cache reset

Add tips for WAF users

---

docs/approvals/deploying-granted/02-setup.mdx

Updated gdeploy version to v0.10.3

[New Release] Update gdeploy to (0.10.3)

---

docs/approvals/deploying-granted/02-setup.mdx

Updated gdeploy version to v0.10.4

[New Release] Update gdeploy to (0.10.4)

---

docs/granted/getting-started.mdx
docs/granted/security.md
docs/granted/usage/headless.md

1. `Release update-docs` github action is failing so had to manually update the version. 
2. Also fix this https://github.com/common-fate/docs/issues/173

Manual update version to 0.6.0

---

docs/granted/usage/assuming-roles.md
docs/granted/usage/console.md

Command outputs for the first time `assume` run was outdated. Add the latest message.

update command output to latest

---

cmd/docscli/commands/generate/generate.go
docs/common-fate/deploying-common-fate/02-setup.mdx
docs/common-fate/providers/add-first-provider/02-cleanup.md
docs/common-fate/providers/registry/commonfate/aws-sso/v2/setup.md
docs/common-fate/providers/registry/commonfate/azure-ad/v1/setup.md
docs/common-fate/providers/registry/commonfate/ecs-exec-sso/v1-alpha1/setup.md
docs/common-fate/providers/registry/commonfate/okta/v1/setup.md
go.mod
go.sum

bump version to v0.12.0

---

docs/granted/usage/automatic-config-generation.md

- add profile-template flag documentation to granted generate/populate command.
https://github.com/common-fate/granted/pull/327

add generate/populate profile-template flag

---

docs/granted/getting-started.mdx
docs/granted/security.md

bump version to 0.7.0

---

docs/granted/usage/console.md

- Docs for https://github.com/common-fate/granted/pull/334
-
1. NA

granted browser command section

---

docs/granted/getting-started.mdx
docs/granted/security.md

Update the Granted version in our documentation.

update granted version to v0.7.1

---

docs/common-fate/configuration/access-rules.md

- Add docs for the terraform provider

add terraform provider docs

---

docs/granted/usage/storing-iam-credentials-securely.md

- Update example output to match reality
- https://github.com/common-fate/granted/pull/364
1.

granted credentials add: Update example command output

---

docs/granted/usage/automatic-config-generation.md

Adds docs for the the improvements in https://github.com/common-fate/granted/pull/359

update profile generation docs

---

docs/granted/getting-started.mdx

Change Granted version to the latest

update docs for 0.9.0

---

aws-sso-usage/org-units.md
docs/common-fate/providers/registry/commonfate/aws-sso/v2/usage.md
docusaurus.config.js

- Adds redirect for intro page (granted-approvals -> common fate)
- Fix wording on one of the generated pages
-
1.

Docs cleanup fixes

---

docs/granted/getting-started.mdx

Updated Granted version to v0.9.1

[New Release] Update versions (0.9.1)

---

docs/common-fate/providers/built-in/aws-sso/v2/setup.md
docs/common-fate/providers/built-in/ecs-exec-sso/v1-alpha1/setup.md
docs/common-fate/sso/aws-sso.mdx

- minor fix removing `❯` from commands for copy
- https://linear.app/common-fate/issue/CF-840/ensure-code-blocks-in-docs-consist-of-code-to-copy-only

minor fix removing `❯` from commands for copy

---

docs/common-fate/providers/add-first-provider/00-first-provider.md

- Minor update based on customer feedback/issue. 
- https://linear.app/common-fate/issue/CF-839/add-to-docs-only-admins-can-create-access-rules

Wording update

---

docs/common-fate/providers/03-deploying.mdx

updates commands in docs to match new `cf` commands

update cf commands

---

common-fate_versioned_docs/version-0.14/security-architecture.md
common-fate_versioned_docs/version-0.15/security-architecture.md
docs/common-fate/security-architecture.md

- Fixes some broken links in docs, in previous versions too
-
1.

fix wrong link

---

docusaurus.config.js

Add configuration for Algolia Docsearch

add site search configuration

---

docs/granted/getting-started.mdx

Updated Granted version to v0.10.0

[New Release] Update versions (0.10.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.11.0

[New Release] Update versions (0.11.0)

---

docs/granted/recipes/access-requests.md

https://github.com/common-fate/granted/pull/391

add docs on CLI request workflow

---

docs/granted/getting-started.mdx

Updated Granted version to v0.11.1

[New Release] Update versions (0.11.1)

---

common-fate_versioned_docs/version-0.14/deploying-common-fate/02-setup.mdx
common-fate_versioned_docs/version-0.15/deploying-common-fate/02-setup.mdx
docs/common-fate/deploying-common-fate/02-setup.mdx

Thankyou to @perpil for helping to identify this!

fix mangled text in git tip

---

docs/granted/recipes/disable-usage-tips.md

> **What changed?**
>  Added docs for disabling usage tips in Granted
> 
> **Why?**
> Documentation needed 
> **How did you test it?**
> Tested the command for disabling usage tips and ran local host
> **Potential risks**
> NA
> **Is patch release candidate?**
>No

Add docs for disabling usage tips in Granted

---

common-fate_versioned_docs/version-0.15/providers/02-setup.mdx
common-fate_versioned_docs/version-0.15/providers/03-deploying.mdx
docs/common-fate/providers/02-setup.mdx
docs/common-fate/providers/03-deploying.mdx

Update doc regarding moving cf commands to subcommand oss

---

common-fate_versioned_docs/version-0.15/providers/02-setup.mdx
docs/common-fate/providers/02-setup.mdx

[New Release] Update cf to (0.4.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.12.0

[New Release] Update versions (0.12.0)

---

docs/provider-development/tutorial/01-create.md

Added documentation to set up .env file for pdk
[Linear](https://linear.app/common-fate/issue/SOL-61/update-pdk-run-describe-docs-to-specify-the-env-file)

pdk .env set up

---

docs/granted/recipes/access-requests.md

added granted login step

---

docs/granted/getting-started.mdx

Updated Granted version to v0.13.1

[New Release] Update versions (0.13.1)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.13.2

[New Release] Update versions (0.13.2)

---

common-fate_versioned_docs/version-0.15/providers/03-deploying.mdx

Update to run cf oss login before deploying provider 
https://linear.app/common-fate/issue/SOL-53/update-cf-deploying-pdk-doc

Updated documentation to cf login before pdk commands

---

docs/granted/configuration.md

Added documentation for quiet mode: `export GRANTED_QUIET=true`

Added documentation for quiet mode

---

common-fate_versioned_docs/version-0.15/providers/02-setup.mdx
docs/common-fate/providers/02-setup.mdx

[New Release] Update cf to (0.5.2)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.14.0

[New Release] Update versions (0.14.0)

---

common-fate_versioned_docs/version-0.14/sso/google.md

Add that the Name ID format should be Email instead of unspecified

Added Name ID format instructions

---

docs/granted/recipes/access-requests.md

- Adds instruction to show how to pass in dashboard url when running `granted login`
-
1.

add instruction to show passing dashboard url as the first param

---

docs/granted/getting-started.mdx

Updated Granted version to v0.14.1

[New Release] Update versions (0.14.1)

---

docs/granted/recipes/access-requests.md

- Adds instructions for using the login --lazy flag to skip interactive login for use in scripts
-
1.

added instructions for lazy

---

docs/granted/getting-started.mdx

Updated Granted version to v0.14.4

[New Release] Update versions (0.14.4)

---

docs/granted/configuration.md
docs/granted/usage/headless.md

Documented vales you can set in  ~/.granted/config file
Fix for issue: https://github.com/common-fate/granted/issues/241

documentation for .granted/config

---

common-fate_versioned_docs/version-0.15/providers/02-setup.mdx
docs/common-fate/providers/02-setup.mdx

[New Release] Update cf to (0.11.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.15.0

[New Release] Update versions (0.15.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.16.0

[New Release] Update versions (0.16.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.17.0

[New Release] Update versions (0.17.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.17.1

[New Release] Update versions (0.17.1)

---

docs/granted/configuration.md
docs/granted/usage/headless.md

docs updates for granted v0.15.0: https://github.com/common-fate/granted/releases/tag/v0.15.0

docs updates for granted v0.15.0

---

.vscode/settings.json
docs/granted/configuration.md
docs/granted/introduction.md
docs/granted/usage/console.md
docs/granted/usage/storing-iam-credentials-securely.md
src/pages/granted-cli/browsers.md

docs updates for granted v0.16.0: https://github.com/common-fate/granted/releases/tag/v0.16.0

docs updates for granted v0.16.0

---

docs/granted/recipes/cache-commands.md

Updated docs for granted v0.17.0 - https://github.com/common-fate/granted/releases/tag/v0.17.0

Added cache commands

---

docs/granted/getting-started.mdx

Updated Granted version to v0.19.0

[New Release] Update versions (0.19.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.18.0

[New Release] Update versions (0.18.0)

---

docs/granted/introduction.md
docs/granted/recipes/credential-process.md
src/pages/granted-cli/browsers.md

Updates for: https://github.com/common-fate/granted/releases/tag/v0.19.0

Updates for Granted v0.19.0

---

docs/granted/getting-started.mdx

Updated Granted version to v0.19.1

[New Release] Update versions (0.19.1)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.19.2

[New Release] Update versions (0.19.2)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.20.0

[New Release] Update versions (0.20.0)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.20.2

[New Release] Update versions (0.20.2)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.20.3

[New Release] Update versions (0.20.3)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.20.5

[New Release] Update versions (0.20.5)

---

docs/granted/getting-started.mdx

Updated Granted version to v0.20.6

[New Release] Update versions (0.20.6)

---

docs/granted/recipes/eks.md

https://github.com/common-fate/granted/issues/591

update eks docs

---

docs/glide/configuration/access-rules.md
docs/glide/configuration/updating.md
docs/glide/deploying-glide/00-deploying-common-fate.md
docs/glide/deploying-glide/04-next-steps.md
docs/glide/introduction.md
docs/glide/providers/built-in/aws-sso/v2/usage.md
docs/glide/sso/00-sso-setup.md
docs/glide/sso/updating-configuration.md

fixed broken glide links
